version: '3'
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./db-data/db:/var/lib/postgresql/data
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: 12345678
  #     POSTGRES_USER: devise_jwt_poc
  #     POSTGRES_DB: jwt_development
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    # depends_on:
    #   - db